services:
  - docker
  - xvfb

sudo: required

branches:
  only:
    - master

jdk:
  - oraclejdk11

addons:
  chrome: stable

env:
  global:
    - E2E_TEST_SUITE='test-e2e-complete'

    - DOCKER_IMAGE=$(mvn help:evaluate -Dexpression=docker.image.name -q -DforceStdout 2> /dev/null)
    - DOCKER_IMAGE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout 2> /dev/null)
    - DOCKER_IMAGE_TMP_VERSION=travis
    - DOCKER_USERNAME=$DOCKER_USERNAME
    - DOCKER_ORGANIZATION=$DOCKER_USERNAME
    - DOCKER_PASSWORD=$DOCKER_PASSWORD

    - MVN_OPTS='-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN'

    - SERVER_PORT=$E2E_SERVER_PORT
    - GIT_HUB_OAUTH_CLIENT=$E2E_GIT_HUB_OAUTH_CLIENT
    - GIT_HUB_OAUTH_SECRET=$E2E_GIT_HUB_OAUTH_SECRET
    - GIT_HUB_REPO_USER_NAME=$E2E_GIT_HUB_REPO_USER_NAME
    - GIT_HUB_REPO_NAME=$E2E_GIT_HUB_REPO_NAME
    - GIT_HUB_WEBHOOK_SECRET=$E2E_GIT_HUB_WEBHOOK_SECRET
    - GIT_HUB_USER=$E2E_GIT_HUB_USER
    - GIT_HUB_USER_PASSWORD=$E2E_GIT_HUB_USER_PASSWORD

stages:
  - Compile and Unit Tests
  - E2E-test

jobs:
  include:
    - stage: Compile and Unit Tests
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - mvn clean install $MVN_OPTS
        - docker tag $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_VERSION $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TMP_VERSION
        - docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TMP_VERSION
      after_failure:
        - curl -u $DOCKER_USERNAME:$DOCKER_PASSWORD -X "DELETE" https://cloud.docker.com/v2/repositories/$DOCKER_ORGANIZATION/$DOCKER_IMAGE/tags/$DOCKER_IMAGE_TMP_VERSION/

    - stage: E2E-test
      before_script:
        - export DISPLAY=:99.0
        - export CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3)
        - mvn initialize $MVN_OPTS -pl front/
        - mvn com.github.eirslett:frontend-maven-plugin:npm@$'start-webdriver' $MVN_OPTS -pl front/
        - export DOCKER_IMAGE_VERSION=$DOCKER_IMAGE_TMP_VERSION
        - docker-compose up -d
      script:
        - mvn com.github.eirslett:frontend-maven-plugin:npm@$E2E_TEST_SUITE $MVN_OPTS -pl front/
      after_failure:
        - curl -u $DOCKER_USERNAME:$DOCKER_PASSWORD -X "DELETE" https://cloud.docker.com/v2/repositories/$DOCKER_ORGANIZATION/$DOCKER_IMAGE/tags/$DOCKER_IMAGE_TMP_VERSION/

    - stage: Deploy Image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TMP_VERSION
        - docker tag $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_TMP_VERSION $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_VERSION
        - docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE:$DOCKER_IMAGE_VERSION
        - curl -u $DOCKER_USERNAME:$DOCKER_PASSWORD -X "DELETE" https://cloud.docker.com/v2/repositories/$DOCKER_ORGANIZATION/$DOCKER_IMAGE/tags/$DOCKER_IMAGE_TMP_VERSION/

#deploy:
#  - provider: elasticbeanstalk
#    region: "eu-central-1"
#    app: "github-oauth"
#    env: "github-oauth-test"
#    bucket_name: "elasticbeanstalk-eu-central-1-712777222880"
#    bucket_path: "github-oauth"
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#      secure: $AWS_SECRET_KEY
#    skip_cleanup: true
#    zip-file: ./server/target/aws-config.zip