language: java

services:
  - docker

branches:
  only:
    - master

jdk:
  - oraclejdk11

deploy:
  - provider: script
    script: "echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin && mvn com.spotify:dockerfile-maven-plugin:push -pl server"
    skip_cleanup: true

  - provider: elasticbeanstalk
    region: "eu-central-1"
    app: "github-oauth"
    env: "github-oauth-test"
    bucket_name: "elasticbeanstalk-eu-central-1-712777222880"
    bucket_path: "github-oauth"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
    skip_cleanup: true
    zip-file: ./server/target/aws-config.zip
