language: java

services:
  - docker

branches:
  only:
    - master

jdk:
  - oraclejdk11

env:
  global:
    - CHROME_VERSION='74.0.3729.6'
    - WEB_DRIVER_LOCATION='./front/src/main/web/node_modules/protractor/bin'
    - E2E_TEST_SUITE='test-e2e-complete'

jobs:
  include:
#    - stage: Compile and Unit Tests
#      script: mvn clean install
    - stage: E2E-test
      install:
        - mvn initialize -pl front/
#        - npm install -g protractor
        - $WEB_DRIVER_LOCATION/webdriver-manager update &&  $WEB_DRIVER_LOCATION/webdriver-manager start --versions.chrome=$CHROME_VERSION --detach  &
      script: mvn com.github.eirslett:frontend-maven-plugin:npm@'$E2E_TEST_SUITE' -pl front/
#    - stage: deploy
#      deploy:
#      - provider: script
#        script:: "echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin && mvn com.spotify:dockerfile-maven-plugin:push -pl server"
#        after_failure: ''
#        skip_cleanup: true

#deploy:


#  - provider: elasticbeanstalk
#    region: "eu-central-1"
#    app: "github-oauth"
#    env: "github-oauth-test"
#    bucket_name: "elasticbeanstalk-eu-central-1-712777222880"
#    bucket_path: "github-oauth"
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#      secure: $AWS_SECRET_KEY
#    skip_cleanup: true
#    zip-file: ./server/target/aws-config.zip
