#language: java

services:
  - docker

branches:
  only:
    - master

jdk:
  - oraclejdk11

addons:
  chrome: stable

env:
  global:
    - WEB_DRIVER_LOCATION='./front/src/main/web/node_modules/protractor/bin'
    - E2E_TEST_SUITE='test-e2e-complete'
    - DOCKER_IMAGE_VERSION=travis
    - DOCKER_PASSWORD=$DOCKER_PASSWORD
    - DOCKER_PASSWORD=$DOCKER_PASSWORD
    - MVN_OPTS='-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN'

stages:
  - Compile and Unit Tests
  - E2E-test

#install: /bin/true

jobs:
  include:
    - stage: Compile and Unit Tests
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - mvn clean deploy -Ddocker.image.version=$DOCKER_IMAGE_VERSION $MVN_OPTS
    - stage: E2E-test
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
        - mvn initialize $MVN_OPTS -pl front/
        - $WEB_DRIVER_LOCATION/webdriver-manager update &&  $WEB_DRIVER_LOCATION/webdriver-manager start --detach  &
      script: mvn com.github.eirslett:frontend-maven-plugin:npm@$E2E_TEST_SUITE $MVN_OPTS -pl front/
      # TODO remove image if failed
      after_failure: /bin/true

#  - provider: elasticbeanstalk
#    region: "eu-central-1"
#    app: "github-oauth"
#    env: "github-oauth-test"
#    bucket_name: "elasticbeanstalk-eu-central-1-712777222880"
#    bucket_path: "github-oauth"
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#      secure: $AWS_SECRET_KEY
#    skip_cleanup: true
#    zip-file: ./server/target/aws-config.zip