language: java

services:
  - docker

branches:
  only:
    - master

deploy:
  provider: script
  script: "echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin && mvn clean deploy"
  skip_cleanup: true
