server:
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: c049f975046962b41a7f
      clientSecret: 319e7ecafbbb8f80742ee160681801a74a12935b
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      scope: repo
    resource:
      userInfoUri: https://api.github.com/user
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:/tmp/git-oauth

poc:
  local-repository-location: /home/sgerard/sandboxes/emasphere
  repoUserName: EMAsphere
  repoName: emasphere
  lock-timeout-in-s: 120
  java-translation-bundle-ignored-paths: src/main/java,src/test,.git,.idea,target/classes