spring:
  main:
    banner-mode: "OFF"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
#          http://i18n-tool.test.sgerard.be:8080
          github:
            client-id: ${GIT_HUB_OAUTH_CLIENT}
            client-secret: ${GIT_HUB_OAUTH_SECRET}
            scope: repo
            redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
          google:
            client-id: "870183340495-t9u7mufdj3ero8ltb2a7fo7k38hdt2ou.apps.googleusercontent.com"
            client-secret: "wGeAqvcjumCxaZCq9aLjCOmT"
            scope:
              - email
              - profile
            redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"
  session:
    jdbc:
      initialize-schema: "ALWAYS"
      schema: "classpath:org/springframework/session/jdbc/schema-@@platform@@.sql"
      table-name: SPRING_SESSION
    store-type: "JDBC"

logging:
  config: "classpath:logback.xml"

springfox:
  documentation:
    swagger:
      v2:
        path: /api/api-doc

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /

be:
  sgerard:
    i18n:
      lock:
        timeout-in-s: 120
      security:
        default-admin-password: ${DEFAULT_ADMIN_PASSWORD:}
      repository:
        java-properties:
          ignored-paths:
            - "**/src/main/java"
            - "**/src/test"
            - ".git"
            - ".idea"
            - "**/target/classes"
            - "**/target/test-classes"
          included-paths:
        json-icu:
          ignored-paths:
          included-paths:
            - "**/src/assets/i18n"
