spring:
  main:
    banner-mode: "OFF"

logging:
  config: "classpath:logback.xml"

springdoc:
  swagger-ui:
    path: "/api/index.html"
  api-docs:
    path: "/api/api-docs"

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /

be:
  sgerard:
    i18n:
      lock:
        timeout-in-s: 120
      security:
        default-admin-password: ${DEFAULT_ADMIN_PASSWORD:}
      repository:
        java-properties:
          ignored-paths:
            - "**/src/main/java"
            - "**/src/test"
            - ".git"
            - ".idea"
            - "**/target/classes"
            - "**/target/test-classes"
          included-paths:
        json-icu:
          ignored-paths:
          included-paths:
            - "**/src/assets/i18n"
