spring:
#  datasource:
#    url: jdbc:h2:file:/tmp/i18n-tool/database/db;DB_CLOSE_ON_EXIT=FALSE;
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: gitHubClientId
            client-secret: gitHubClientSecret
be:
  sgerard:
    i18n:
      base-directory: /tmp/i18n-tool
      security:
        default-admin-password: admin
