spring:
  main:
    banner-mode: "OFF"
  jpa:
      open-in-view: false
      hibernate:
          ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_HUB_OAUTH_CLIENT}
            client-secret: ${GIT_HUB_OAUTH_SECRET}
            scope: repo
            redirect-uri-template: "{baseUrl}/auth/oauth2/code/{registrationId}"
  session:
    jdbc:
      initialize-schema: "ALWAYS"
      schema: "classpath:org/springframework/session/jdbc/schema-@@platform@@.sql"
      table-name: SPRING_SESSION
    store-type: "JDBC"

logging:
  config: "classpath:logback.xml"

springfox:
  documentation:
    swagger:
      v2:
        path: /api/api-doc

be:
  sgerard:
    i18n:
      repoUserName: ${GIT_HUB_REPO_USER_NAME}
      repoName: ${GIT_HUB_REPO_NAME}
      lock-timeout-in-s: 120
      java-translation-bundle-ignored-paths: "**/src/main/java,**/src/test,.git,.idea,**/target/classes,/front/,**/target/test-classes"
      json-icu-translation-bundle-dirs: "**/src/assets/i18n"
      git-hub-webhook-secret: ${GIT_HUB_WEBHOOK_SECRET}
      locales:
          - en
          - fr
          - nl