spring:
  main:
    banner-mode: "OFF"
    allow-circular-references: true
  data:
    mongodb:
      auto-index-creation: false

logging:
  config: "classpath:logback.xml"

springdoc:
  swagger-ui:
    path: "/api/index.html"
  api-docs:
    path: "/api/api-docs"
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /


server:
  error:
    path: '/error'

be:
  sgerard:
    i18n:
      lock:
        timeout-in-ms: 120000
      security:
        default-admin-password: ${DEFAULT_ADMIN_PASSWORD:}
      repository:
        java-properties:
          ignored-paths:
            - "**/src/main/java"
            - "**/src/test"
            - ".git"
            - ".idea"
            - "**/target/classes"
            - "**/target/test-classes"
          included-paths:
        json-icu:
          ignored-paths:
          included-paths:
            - "**/src/assets/i18n"

mongock:
  change-logs-scan-package: be.sgerard.i18n.migration.persistence