spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_HUB_OAUTH_CLIENT}
            client-secret: ${GOOGLE_HUB_OAUTH_SECRET}
            scope:
              - email
              - profile
            redirectUri: "{baseUrl}/auth/oauth2/code/{registrationId}"

be:
  sgerard:
    i18n:
      security:
        google:
          restricted-domains:
