spring:
  main:
    banner-mode: "OFF"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_HUB_OAUTH_CLIENT}
            client-secret: ${GIT_HUB_OAUTH_SECRET}
            scope: repo
            redirect-uri-template: "{baseUrl}/auth/oauth2/code/{registrationId}"
  #          google:
  #            client-id: "241420143849-soe1koqhh6gh9tauqcnvrfdplag1cqce.apps.googleusercontent.com"
  #            client-secret: "ahUSO_-ywDc6eKm6ygEOx6xi"
  #            scope: openid
  #            redirect-uri-template: "{baseUrl}/auth/oauth2/code/{registrationId}"
  session:
    jdbc:
      initialize-schema: "ALWAYS"
      schema: "classpath:org/springframework/session/jdbc/schema-@@platform@@.sql"
      table-name: SPRING_SESSION
    store-type: "JDBC"

logging:
  config: "classpath:logback.xml"

springfox:
  documentation:
    swagger:
      v2:
        path: /api/api-doc

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /

be:
  sgerard:
    i18n:
      lock-timeout-in-s: 120
      security:
        default-admin-password: ${DEFAULT_ADMIN_PASSWORD:}
      repository:
        java-properties:
          ignored-paths:
            - "**/src/main/java"
            - "**/src/test"
            - ".git"
            - ".idea"
            - "**/target/classes"
            - "**/target/test-classes"
          included-paths:
        json-icu:
          ignored-paths:
          included-paths:
            - "**/src/assets/i18n"
