spring:
  datasource:
    url: jdbc:h2:file:/tmp/git-oauth/database/db;DB_CLOSE_ON_EXIT=FALSE;
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: gitHubClientId
            client-secret: gitHubClientSecret
be:
  sgerard:
    i18n:
      base-directory: /tmp/git-oauth
      repoUserName: sebge2
      repoName: i18n-tool
      git-hub-webhook-secret: webhookSecret
      default-admin-password: adminPassword