be:
  sgerard:
    i18n:
      base-directory: ${BASE_REPOSITORY:/tmp/i18n-tool}
      security:
        default-admin-password: admin
      repository:
        auto-sync-frequency: '0 0 * * * *'
      scheduled-task:
        cleanup-frequency: '0 0 * * * *'
        cleanup-executions-older-than-days: 31

springdoc:
  api-docs:
    enabled: true