version: "3.7"
services:
  mongodb:
    image: 'mongo:4.4.0'
    container_name: 'mongodb'
    ports:
      - "27017-27019:27017-27019"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - ./mongo-data:/data/db